{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "abd0b088",
   "metadata": {},
   "source": [
    "Предположим, мы написали программу. Она даже запустилась и вроде даже что-то сделала. Но в один прекрасный момент всё вылетело, а в терминале вылезло непонятное сообщение:\n",
    "\n",
    "```python\n",
    "Traceback (most recent call last):\n",
    "File \"<stdin>\", line 1, in <module>\n",
    "ValueError: invalid literal for int() with base 10: \"odin\"\n",
    "```\n",
    "\n",
    "Эта ошибка относится к типу **исключительных ситуаций**. Исключительные ситуации порой возникают в случаях, когда вы написали код правильно, он запустился и отработал своё, а запустив код на следующий день, вы видите ошибку. \n",
    "\n",
    "Но как? В прошлый раз всё ведь запускалось без ошибок…\n",
    "\n",
    "Дело в том, что исключения могут возникнуть не только из-за ошибок в написании кода, а ещё и от взаимодействия пользователя с вашей программой, от состояния системы, на которой она запущена, погоды или ретроградного Меркурия. Да от чего угодно помимо вашего кода! \n",
    "\n",
    "Итак, в этом юните вы узнаете, как работать с исключительными ситуациями или же исключениями в языке Python.\n",
    "\n",
    "**Исключения** — это такие ошибки, которые возникают не во время компиляции программы, а в процессе её исполнения, в случаях, если что-то идёт не так.\n",
    "\n",
    "После возникновения исключения программа попытается экстренно завершить работу или перейти к обработчику исключения, если такой есть. Поскольку Python — интерпретируемый язык, то, по сути, исключения и вставляют нам палки в колёса, прерывая выполнение программы.\n",
    "\n",
    "Ошибки бывают двух видов:\n",
    "\n",
    "- **отлавливаемые** — все, что наследуются от класса Exception;\n",
    "- **не отлавливаемые** — SystemExit, KeyboardInterrupt и т. д.\n",
    "  \n",
    "Заучивать их все не стоит — только зря потратите время, потому как на самом деле этих ошибок может быть множество. Например, в отдельной библиотеке есть собственные исключения."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2cac5d13",
   "metadata": {},
   "source": [
    "Давайте же посмотрим на пример кода, который вызывает исключение.\n",
    "\n",
    "<table>\n",
    "    <th>Название исключения</th>\n",
    "    <th>Когда возникает</th>\n",
    "    <th>Название в Python</th>\n",
    "    <tr>\n",
    "        <td>Исключение, возникающее при делении на 0</td>\n",
    "        <td>При делении на ноль.</td>\n",
    "        <td>ZeroDivisionError</td>\n",
    "    </tr>\n",
    "    <tr>\n",
    "        <td>Ошибка значения</td>\n",
    "        <td>При невозможности привести один тип к другому.</td>\n",
    "        <td>ValueError</td>\n",
    "    </tr>\n",
    "    <tr>\n",
    "        <td>Файл не найден</td>\n",
    "        <td>Если попытаться открыть файл для чтения, который не был создан.</td>\n",
    "        <td>FileNotFoundError</td>\n",
    "    </tr>\n",
    "    <tr>\n",
    "        <td>Недостаточно прав</td>\n",
    "        <td>Если попытаться открыть файл из корневых каталогов при запуске программы не от имени администратора.</td>\n",
    "        <td>PermissionError</td>\n",
    "    </tr>\n",
    "</table>\n",
    "\n",
    "Это лишь несколько из них. [Список всех исключений](https://docs.python.org/3/library/exceptions.html) доступен в документации. Можете ознакомиться с ним, чтобы быть в курсе, какие ошибки могут возникнуть в простых программах."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "17eaab38",
   "metadata": {},
   "source": [
    "```python\n",
    "print(\"Перед исключением\")\n",
    "c = 1 / 0  # Здесь что-то не так….\n",
    "print(\"После исключения\")\n",
    "```\n",
    "\n",
    "В консоли мы увидим следующий результат:\n",
    "\n",
    "```python\n",
    "Перед исключением\n",
    "Traceback (most recent call last):\n",
    "File \"<stdin>\", line 1, in <module>\n",
    "ZeroDivisionError: division by zero\n",
    "```\n",
    "\n",
    "Строка «После исключения» не будет выведена на экран: как только интерпретатор дойдёт до строчки c = 1 / 0, он экстренно завершит работу и выведет нам сообщение об ошибке деления на ноль.\n",
    "\n",
    "В этом примере мы чётко видим, что может возникнуть ошибка. Но в большинстве случаев это бывает не столь очевидно. Поэтому давайте слегка поменяем наш код:\n",
    "\n",
    "```python\n",
    "print(\"Перед исключением\")\n",
    "# теперь пользователь сам вводит числа для деления\n",
    "a = int(input(\"a: \"))\n",
    "b = int(input(\"b: \"))\n",
    "c = a / b  # здесь может возникнуть исключение деления на ноль\n",
    "print(c)  # печатаем c = a / b если всё хорошо\n",
    "print(\"После исключения\")\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "acafaefc",
   "metadata": {},
   "source": [
    "После выполнения этого кода у пользователя может возникнуть такая же ошибка, если он введёт b = 0.\n",
    "\n",
    "Как же сделать так, чтобы программа не вылетала при ошибке и продолжала свою работу? \n",
    "\n",
    "Очень просто! Для этого и нужна конструкция **try-except**.\n",
    "\n",
    "Давайте посмотрим на следующий код:\n",
    "\n",
    "```python\n",
    "try:  # Добавляем конструкцию try-except для отлова нашей ошибки\n",
    "    print(\"Перед исключением\")\n",
    "    # теперь пользователь сам вводит числа для деления\n",
    "    a = int(input(\"a: \"))\n",
    "    b = int(input(\"b: \"))\n",
    "    c = a / b  # здесь может возникнуть исключение деления на ноль\n",
    "    print(c)  # печатаем c = a / b если всё хорошо\n",
    "except ZeroDivisionError as e: # Добавляем тип именно той ошибки, которую хотим отловить.     \n",
    "    print(e)  # Выводим информацию об ошибке\n",
    "    print(\"После исключения\")\n",
    " \n",
    "print(\"После После исключения\")\n",
    "```\n",
    "\n",
    "В данном случае тоже может возникнуть ошибка деления на ноль, если пользователь введёт b = 0. Поэтому мы отлавливаем ошибку ZeroDivisionError. В блоке try помещается «опасный» кусок кода, который может вызывать исключения, а в блоке except указывается класс ошибки, которую мы хотим отловить, а затем помещается код, который нужно выполнить в случае возникновении ошибки. \n",
    "\n",
    "После возникновении ошибки код в блоке try прервётся, перейдёт в блок except, а затем продолжит выполняться дальше — программа не вылетает, как это было без обработчика исключений. В этом и есть главная суть конструкции try-except.\n",
    "\n",
    "Это ещё не всё! Есть также блоки finally и else. Код в блоке else выполнялся после завершения цикла. С try-except есть нечто похожее. Посмотрите на пример кода ниже.\n",
    "\n",
    "Можно так:\n",
    "```python\n",
    "try:\n",
    "    *ваш код*\n",
    "except Ошибка:\n",
    "    *Код отлова*\n",
    "else:\n",
    "    *Код, который выполнится если всё хорошо прошло в блоке try*\n",
    "finally:\n",
    "    *Код, который выполнится по любому*\n",
    "```\n",
    "\n",
    "**Важно**! Обратите внимание на отступы — код внутри конструкции сдвинут на второй уровень вложенности."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a406e88",
   "metadata": {},
   "source": [
    "Мы можем вызывать ошибки самостоятельно с помощью конструкции **raise**. Используется это, как правило, для отладки кода и остановки программы в критических ситуациях.\n",
    "\n",
    "Например:\n",
    "\n",
    "```python\n",
    "age = int(input(\"Сколько тебе лет?\"))\n",
    "\n",
    "if age > 100 or age <= 0:\n",
    "    raise ValueError(\"Тебе не может быть столько лет\")\n",
    " \n",
    "print(f\"Тебе {age} лет!\") # Возраст выводится только если пользователь ввёл правильный возраст.\n",
    "``` \n",
    "\n",
    "Здесь ошибка ValueError возникнет, если пользователь ввёл неправильный возраст, и остановит работу программы, выдав в консоль:\n",
    "\n",
    "```python\n",
    "raise ValueError(\"Тебе не может быть столько лет\")\n",
    "Traceback (most recent call last):\n",
    "File \"<stdin>\", line 1, in <module>\n",
    "ValueError: Тебе не может быть столько лет\n",
    "``` \n",
    "\n",
    "В консоль выводится именно то сообщение, которое вы передадите в аргумент конструктора класса исключения. Если не хотите никаких сообщений, то просто оставьте скобки пустыми. \n",
    "\n",
    "Стоит отметить, что отлавливать вызываемые с помощью raise ошибки тоже можно.\n",
    "\n",
    "Например:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    age = int(input(\"Сколько тебе лет?\"))\n",
    "\n",
    "    if age > 100 or age <= 0:\n",
    "        raise ValueError(\"Тебе не может быть столько лет\")\n",
    "\n",
    "    # Возраст выводится только если пользователь ввёл правильный возраст.\n",
    "    print(f\"Тебе {age} лет!\")\n",
    "except ValueError:\n",
    "    print(\"Неправильный возраст\")\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8007a70c",
   "metadata": {},
   "source": [
    "Давайте кратко подведём итоги:\n",
    "\n",
    "**Исключения — это ошибки**, которые выбрасываются при неправильной работе программы, и останавливают её выполнение, если они не обработаны.\n",
    "\n",
    "Конструкция **try-except** выглядит следующим образом и служит для обработки исключений:\n",
    "```python\n",
    "try:\n",
    "    *код, который может вызвать ту или иную ошибку*\n",
    "except *ошибка*:\n",
    "    *код, который выполнится в случае возникновения ошибки*\n",
    "else:\n",
    "    *код, который выполнится только в случае если в try ничего не сломалось*\n",
    "finally:\n",
    "    *код, который выполнится по любому*\n",
    "```\n",
    "\n",
    "Блоки **finally и else** являются не обязательными, но могут быть использованы для вашего удобства. \n",
    "- Код из блока finally выполняется в любом случае, независимо от исхода в блоках try-except. \n",
    "- Код из блока else выполняется только в случае успешного выполнения кода в try.\n",
    "- \n",
    "Выбрасывать ошибки можно и по своему желанию с помощью конструкции **raise *Тип ошибки*** (сообщение, которое нужно вывести в консоль)."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myConda_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
